backend/models/User.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property int $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $avatar
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 */
class User extends \yii\db\ActiveRecord
{
    const STATUS_ACTIVE = 10;
    const STATUS_DELETED = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password_hash', 'email', 'status'], 'required'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'email', 'avatar'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'                   => 'ID',
            'username'             => '用户名',
            'auth_key'             => '认证密钥',
            'password_hash'        => '密码',
            'password_reset_token' => '重置密码token',
            'email'                => '邮箱',
            'avatar'               => '头像',
            'status'               => '状态',
            'created_at'           => '注册时间',
            'updated_at'           => '最后登录时间',
        ];
    }

    public static function getStatuses()
    {
        return [
            self::STATUS_ACTIVE  => '正常',
            self::STATUS_DELETED => '禁用',
        ];
    }

}

common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%admin_user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\User;
use backend\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $errors = $model->getErrors();
            $err = '';
            foreach ($errors as $v) {
                $err .= $v[0] . '<br>';
            }
            yii::$app->getSession()->setFlash('hintInfo', $err);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $ids = explode(',', $id);
        foreach ($ids as $vo) {
            $this->findModel($vo)->delete();
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">
    <?php $form = ActiveForm::begin([
            'fieldConfig' => [
                'template' => "{label}<div class='col-md-6'>{input}\n{error}\n{hint}</div>",
            ],
            'options' => [
                'class' => 'form-horizontal m-t',
                'id'=>'signupForm',
            ],
        ]); ?>
        <?= $form->field($model, 'username')->textInput()->label(null, ['for'=>'firstname', 'class'=>'col-sm-2 control-label']) ?>
        <?= $form->field($model, 'password_hash')->textInput()->label(null, ['for'=>'firstname', 'class'=>'col-sm-2 control-label']) ?>
        <?= $form->field($model, 'email')->textInput()->label(null, ['for'=>'firstname', 'class'=>'col-sm-2 control-label']) ?>
        <?= $form->field($model, 'status')->dropDownList(
            ['10'=>'正常','0'=>'禁用'],
            ['prompt'=>'请选择',]
        )->label(null, ['for'=>'firstname', 'class'=>'col-sm-2 control-label']) ?>
        <div class="form-group">
            <div class="col-sm-8 col-sm-offset-3">
                <button class="btn btn-success" type="submit">保存</button>
                <!-- <a class="btn btn-default" onclick="window.history.back();">返回</a> -->
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>
</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'class' => 'well form-inline',
            'id'=>'signupForm',
        ],
    ]); ?>
    用户ID：
    <input class="form-control" type="text" id="usersearch-id" name="UserSearch[id]" style="width: 200px;" value="" >
    用户名：
    <input class="form-control" type="text" id="usersearch-username" name="UserSearch[username]" style="width: 200px;" value="">
    邮箱：
    <input class="form-control" type="text" id="usersearch-email" name="UserSearch[email]" style="width: 200px;" value="" >
    状态：
    <select class="form-control" id="usersearch-status" name="UserSearch[status]">
        <option value="">默认</option>
        <option value="10">正常</option>
        <option value="0">禁用</option>
    </select>
    <input type="submit" class="btn btn-primary" value="搜索">
    <input type="reset" class="btn btn-danger" value="清空">
    <?php ActiveForm::end(); ?>
</div>

backend/views/user/create.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>
<div class="wrapper wrapper-content animated fadeIn" >
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title" style="padding: 0px;border-top: 0px;">
                    <ul class="nav nav-tabs">
                        <li class=""><a href="<?= Url::to(['user/index'])?>">前台用户</a></li>
                        <li class="active"><a href="<?= Url::to(['user/create'])?>">创建用户</a></li>
                    </ul>
                </div>
                <div class="ibox-content" style="border-top: 0px;">
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                        	<?= $this->render('_form', [
                        	    'model' => $model,
                        	]) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use backend\models\AdminUser;
use backend\models\User;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    #w0{text-align: center;}
    #w0 table th{text-align: center;}
    #w0 .summary{text-align: left;}
</style>
<div class="wrapper wrapper-content animated fadeIn" >
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title" style="padding: 0px;border-top: 0px;">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="tabs_panels.html#tab-1">前台用户</a></li>
                        <li><a href="<?= Url::to(['user/create']) ?>">创建用户</a></li>
                    </ul>
                </div>
                <div class="ibox-content" style="border-top: 0px;">
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="user-index">
                                <?php  echo $this->render('_search', ['model' => $searchModel]); ?>
                                <p>
                                    <button type="btn" class="btn btn-success">批量操作</button>
                                    <?= Html::a("删除", "javascript:void(0);", [
                                        "class" => "btn btn-danger mybtn",
                                        'action' => Url::to(['user/delete']),
                                    ]) ?>
                                    <button type="btn" class="btn btn-success">批量操作</button>
                                </p>

                                <?php
                                    $js = <<<js
                                    $(document).on('click', '.mybtn', function () {
                                        //可以把选中的id通过ajax提交到后端，然后借助yii的deleteAll()语句进行删除或操作
                                        var keys = $("#grid").yiiGridView("getSelectedRows");
                                        var ids = keys.join(",");
                                        var action = $(this).attr("action")+"&id="+ids;
                                        console.log(action);
                                        $.post(action, function(data){
                                            // console.log(data);
                                        });
                                    });
js;
                                    $this->registerJs($js);
                                ?>
                                <?= GridView::widget([
                                    'dataProvider' => $dataProvider,
                                    'filterModel' => $searchModel,
                                    "options" => ["class" => "grid-view","style"=>"overflow:auto", "id" => "grid"],
                                    'columns' => [
                                        [
                                            'class' => 'yii\grid\SerialColumn',
                                            'class' => 'yii\grid\CheckboxColumn',
                                        ],

                                        [
                                           'attribute' => 'id',
                                           'headerOptions'=> ['width'=> '200'],
                                        ],
                                        'username',
                                        'email:email',
                                        [
                                            'attribute' => 'status',
                                            // 'label' => '状态',
                                            'value' => function ($model) {
                                                if($model->status == User::STATUS_ACTIVE){
                                                    return '正常';
                                                }else if( $model->status == User::STATUS_DELETED ){
                                                    return '禁用';
                                                }
                                            },
                                            'filter' => User::getStatuses(),
                                        ],
                                        [
                                            'attribute' => 'updated_at',
                                            'format' => ['date', 'php:Y-m-d H:i:s'],
                                            'filter' => Html::activeInput('text', $searchModel, 'update_start_at', [
                                                    'class' => 'form-control layer-date',
                                                    'placeholder' => '',
                                                    'onclick' => "laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"
                                                ]) . Html::activeInput('text', $searchModel, 'update_end_at', [
                                                    'class' => 'form-control layer-date',
                                                    'placeholder' => '',
                                                    'onclick' => "laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"
                                                ]),
                                        ],
                                        [
                                            'class' => 'yii\grid\ActionColumn',
                                            'template' => '{view} {update} {delete}',
                                            'buttons' => [
                                                'view'=>function ($url, $model, $key) {
                                                    return Html::a('查看', ['user/view', 'id' => $model->id], ['class' => ""]);
                                                },
                                                'update'=>function ($url, $model, $key) {
                                                    return Html::a('编辑', ['user/update', 'id' => $model->id], ['class' => ""]);
                                                },
                                                'delete'=>function ($url, $model, $key) {
                                                    return Html::tag('span', '删除', [
                                                        'class' => "text-danger confirm",
                                                        'action' => Url::to(['user/delete','id'=>$model->id]),
                                                        'style' => ['cursor' => 'pointer'],
                                                    ]);
                                                }
                                            ],
                                        ],
                                        ],
                                ]); ?>
                                <p>
                                    <button type="btn" class="btn btn-success">批量操作</button>
                                    <?= Html::a("删除", "javascript:void(0);", [
                                        "class" => "btn btn-danger mybtn",
                                        'action' => Url::to(['user/delete']),
                                    ]) ?>
                                    <button type="btn" class="btn btn-success">批量操作</button>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/user/update.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>
<div class="wrapper wrapper-content animated fadeIn" >
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title" style="padding: 0px;border-top: 0px;">
                    <ul class="nav nav-tabs">
                        <li class=""><a href="<?= Url::to(['user/index'])?>">前台用户</a></li>
                        <li class="active"><a href="#">编辑用户</a></li>
                    </ul>
                </div>
                <div class="ibox-content" style="border-top: 0px;">
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                        	<?= $this->render('_form', [
                        	    'model' => $model,
                        	]) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/user/view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;
?>
<div class="wrapper wrapper-content animated fadeIn" >
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title" style="padding: 0px;border-top: 0px;">
                    <ul class="nav nav-tabs">
                        <li class=""><a href="<?= Url::to(['user/index'])?>">前台用户</a></li>
                        <li class="active"><a href="#">用户详情</a></li>
                    </ul>
                </div>
                <div class="ibox-content" style="border-top: 0px;">
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="user-view">
                                <p>
                                    <?= Html::a('编辑', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                                    <?= Html::a('删除', ['delete', 'id' => $model->id], [
                                        'class' => 'btn btn-danger',
                                        'data' => [
                                            'confirm' => 'Are you sure you want to delete this item?',
                                            'method' => 'post',
                                        ],
                                    ]) ?>
                                </p>
                                <?= DetailView::widget([
                                    'model' => $model,
                                    'attributes' => [
                                        'id',
                                        'username',
                                        'auth_key',
                                        'password_hash',
                                        'password_reset_token',
                                        'email:email',
                                        'avatar',
                                        'status',
                                        'created_at',
                                        'updated_at',
                                    ],
                                ]) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>