backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    // public $layout = false;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //这里一定要加
                'only' => ['login', 'index', 'main', 'logout'],
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'main'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'backend\components\CaptchaAction',
                // 'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,//本行可能引起更换验证码失效，必须刷新浏览器
                'backColor' => 0x66b3ff,//背景颜色
                'maxLength' => 4,//最大显示个数
                'minLength' => 4,//最少显示个数
                'padding' => 4,//验证码字体大小，数值越小字体越大
                'height' => 34,//高度
                'width' => 300,//宽度
                'foreColor' => 0xffffff,//字体颜色
                'offset' => 60,//设置字符偏移量
            ],
        ];
    }
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->renderPartial('index');
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionMain()
    {
        return $this->render('main', ['system_info'=>system_info()]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    // 'logout' => ['post'],
                ],
            ],
            [
                // 页面缓存
                'class' => 'yii\filters\PageCache',
                'only' => ['index'],
                'duration' => 60,
                'variations' => [
                    Yii::$app->language,
                    Yii::$app->request->get('page'),
                    Yii::$app->request->get('cid'),
                    Yii::$app->request->get('search'),
                ],
                'dependency' => [
                    'class' => 'yii\caching\DbDependency',
                    'sql' => 'SELECT COUNT(*) FROM feehi_article',
                ],
            ],
            [
                // HTTP 缓存
                'class' => 'yii\filters\HttpCache',
                'only' => ['article'],
                'lastModified' => function ($action, $params) {
                    $q = new \yii\db\Query();
                    return $q->from('feehi_article')->max('update_time');
                },
                'etagSeed' => function ($action, $params) {
                    $article = \backend\models\Article::findOne(Yii::$app->request->get('id'));
                    return serialize([$article->post_title, $article->post_content]);
                },
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $cid = empty(Yii::$app->request->get('cid')) ? 0 : intval(Yii::$app->request->get('cid'));
        $search = empty(Yii::$app->request->get('search')) ? '' : Yii::$app->request->get('search');

        $where = [
            'post_status'=>1,
            'post_type'=>1,
        ];
        if ($cid) {
            $where['category_id'] = $cid;
        }

        // 关联查询
        $query = \backend\models\Article::find()
                ->select(['feehi_article.id', 'post_title', 'user_id', 'post_hits', 'post_content', 'post_excerpt', 'published_time'])
                ->joinWith([
                    'adminUser' => function($query){
                        $query->select(['id', 'username']);
                    },
                    'categorys'
                ])
                ->where($where)

                ->groupBy(['post_id'])
                ->orderBy('published_time DESC');
        if ($search) {
            $query->andWhere(['like', 'post_title', $search]);
        }

        // pp($query->createCommand()->getRawSql());
        $countQuery = clone $query;
        $pages = new \yii\data\Pagination(['totalCount' => $countQuery->count()]);
        $pages->defaultPageSize = 10;
        $models = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();

        return $this->render('index', [
             'models' => $models,
             'pages' => $pages,
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionElasticSearch()
    {
        // elasticsearch 测试
        if (false) {
            $searchModel = \frontend\models\ArticleElasticSearch::find()->query([
                "multi_match" => [
                    "query" => '更新',
                    "fields" => ["post_title", "post_excerpt"]
                ],
            ]);
            $highlight = [
                "pre_tags" => ["<b style='color: red;' >"],
                "post_tags" => ["</b>"],
                "fields" => [
                    "post_title" => new \stdClass(),
                    "post_excerpt" => new \stdClass()
                ]
            ];

            $searchModel = $searchModel->highlight($highlight)->asArray()->all();
            pp($searchModel);
        }

        // 批量添加数据
        if (false) {
            set_time_limit(0);
            $connection = \Yii::$app->db;
            $command = $connection->createCommand("SELECT post_id FROM feehi_category_article ORDER BY id DESC limit 1");
            $lastId = $command->queryOne()['post_id'];
            $endId = $lastId + 500;
            for ($i = $lastId; $i <= $endId ; $i++) {
                $sql = "INSERT INTO `yiiblog`.`feehi_category_article` (`post_id`, `category_id`, `list_order`, `status`) VALUES ($i, '1', '10000', '1')";
                $command = $connection->createCommand($sql);
                $command->execute();
            }
            pp(true);
        }

        return $this->render('elasticSearch');
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionArticle($id)
    {
        $model = \backend\models\Article::findOne($id);
        $model->post_hits++;
        $model->save();

        // 缓存依赖
        $dependency = new \yii\caching\DbDependency(['sql' => 'SELECT post_title,published_time FROM feehi_article WHERE id = '.$id]);
        if (Yii::$app->cache->get('artcle_model')) {
            $article = Yii::$app->cache->get('artcle_model');
        } else {
            $article = \backend\models\Article::find()
                    ->select(['feehi_article.id', 'post_title', 'user_id', 'post_hits', 'post_content', 'post_excerpt', 'published_time'])
                    ->joinWith([
                        'adminUser' => function($query){
                            $query->select(['id', 'username']);
                        },
                        'categorys'
                    ])
                    ->where(['feehi_article.id'=>$id])
                    ->groupBy(['post_id'])
                    ->orderBy('published_time DESC')
                    ->asArray()
                    ->all();
            // 数据缓存
            Yii::$app->cache->set('artcle_model', $article, 30*60, $dependency);
        }

        // pp($article);
        return $this->render('article', ['article'=>$article]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            $object = Yii::$app->request->post('SignupForm')['email'];
            // $object = '798314049@qq.com';
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    // return $this->goHome();
                    $title         = '[琯琯博客] 邮箱激活通知';
                    $sender        = '琯琯博客';
                    $verifyCode    = json_decode($user->email_verify, 1)['verify_token'];
                    $verifyAddress = Yii::$app->urlManager->createAbsoluteUrl(['site/verify-email', 'verifyCode' => $verifyCode]);
                    // 执行任务时避免外部依赖(数据必须直接给)
                    $queueId = Yii::$app->queue->delay(3)->push(new \frontend\components\SendEmailJob([
                        'object'        => $object,
                        'title'         => $title,
                        'verifyAddress' => $verifyAddress,
                        'sender'        => $sender,
                    ]));
                    if ($queueId) {

backend/views/site/500.php
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="renderer" content="webkit">

    <title>素材火www.sucaihuo.com - 500错误</title>
    <meta name="keywords" content="H+后台主题,后台bootstrap框架,会员中心主题,后台HTML,响应式后台">
    <meta name="description" content="H+是一个完全响应式，基于Bootstrap3最新版本开发的扁平化主题，她采用了主流的左右两栏式布局，使用了Html5+CSS3等现代技术">

    <link href="css/bootstrap.min.css?v=3.4.0" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css?v=4.3.0" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css?v=2.2.0" rel="stylesheet">

</head>

<body class="gray-bg">


    <div class="middle-box text-center animated fadeInDown">
        <h1>500</h1>
        <h3 class="font-bold">服务器内部错误</h3>

        <div class="error-desc">
            服务器好像出错了...
            <br/>您可以返回主页看看
            <br/><a href="index.html" class="btn btn-primary m-t">主页</a>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="js/jquery-2.1.1.min.js"></script>
    <script src="js/bootstrap.min.js?v=3.4.0"></script>

    <script type="text/javascript" src="http://tajs.qq.com/stats?sId=9051096" charset="UTF-8"></script><!--统计代码，可删除-->

</body>

</html>

backend/views/site/error.php
<div class="middle-box text-center animated fadeInDown">
    <h1>404</h1>
    <h3 class="font-bold">页面未找到！</h3>

    <div class="error-desc">
        抱歉，页面好像去火星了~
    </div>
</div>

backend/views/site/index - 副本.php
<?php
use backend\assets\MyAppAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

// $this 代表视图对象
MyAppAsset::register($this);
$this->params['breadcrumbs'][] = $this->title;
$this->title = '主页';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <meta name="keywords" content="H+后台主题,响应式后台">
    <meta name="description" content="H+是一个完全响应式，基于Bootstrap3最新版本开发的扁平化主题。">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <?php $this->beginBody() ?>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">

                        <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="/static/img/profile_small.jpg" />
                             </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                                <span class="text-muted text-xs block">超级管理员 <b class="caret"></b></span> </span>
                                <span class="clear"> <span class="block m-t-xs">
                                    <strong class="font-bold">
                                        <?= Yii::$app->user->identity ? Yii::$app->user->identity->username : ''; ?>
                                    </strong>
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="<?= Url::to(['site/logout']) ?>">安全退出</a>
                                </li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            琯琯
                        </div>

                    </li>
                    <li>
                        <a class="J_menuItem" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">设置管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['setting/website']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">网站设置</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['setting/email']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">邮箱设置</span></a>
                            </li>

                        </ul>
                    </li>
                    <li>
                        <a class="J_menuItem" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">用户管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['user/index']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">前台用户</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['admin-user/index']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">后台用户</span></a>
                            </li>
                        </ul>
                    </li>
                    <li class="">
                        <a class="J_menuItem" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">权限管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level collapse" aria-expanded="false" style="height: 0px;">
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['admin/assignment']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">分配权限</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['admin/role']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">角色列表</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['admin/permission']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">权限列表</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['admin/route']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">路由列表</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['admin/menu']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">菜单列表</span></a>
                            </li>
                            <!-- <li>
                                <a class="J_menuItem" href="<?= Url::to(['admin/rule']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">规则列表</span></a>
                            </li> -->
                            <!-- <li>
                                <a class="J_menuItem" href="<?= Url::to(['admin/user']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">用户列表</span></a>
                            </li> -->
                        </ul>
                    </li>
                    <li>
                        <a class="J_menuItem" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">内容管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['category/index']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">分类管理</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['article/index']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">文章管理</span></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="J_menuItem" href="<?= Url::to(['friend-link/index']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">友情连接</span></a>
                    </li>
                    <li>
                        <a class="J_menuItem" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">菜单管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['menu/index', 'type'=>1]) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">前台导航</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['menu/index', 'type'=>0]) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">后台菜单</span></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="J_menuItem" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">缓存管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['clear/frontend']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">清除前台</span></a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="<?= Url::to(['clear/backend']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">清除后台</span></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="J_menuItem" href="<?= Url::to(['admin-log/index']) ?>" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">日志管理</span></a>
                    </li>
                    <li>
                        <a class="J_menuItem" href="gii" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">Gii</span></a>
                    </li>
                    <li>
                        <a class="J_menuItem" href="debug" data-index="4"><i class="fa fa-columns"></i> <span class="nav-label">Debug</span></a>
                    </li>
                    <?php $menuData = dataTree(); ?>
                    <?php foreach ($menuData as $k => $v): ?>
                    <li>
                        <?php if ($v['children']): ?>
                            <a class="J_menuItem" data-index="<?= $v['id'] ?>"><i class="<?= $v['data'] ?>"></i> <span class="nav-label"><?= $v['name'] ?></span><span class="<?= empty($v['children']) ? '' : 'fa arrow'; ?>"></span></a>
                        <?php else: ?>
                            <a class="J_menuItem" data-index="<?= $v['id'] ?>" href="<?= Url::to([trim($v['route'], '/')]) ?>"><i class="<?= $v['data'] ?>"></i> <span class="nav-label"><?= $v['name'] ?></span><span class="<?= empty($v['children']) ? '' : 'fa arrow'; ?>"></span></a>
                        <?php endif ?>

                        <ul class="nav nav-second-level">
                            <?php foreach ($v['children'] as $kk => $vv): ?>
                            <li>
                                <a class="J_menuItem" data-index="<?= $vv['id'] ?>" href="<?= Url::to([trim($vv['route'], '/')]) ?>"><i class="<?= $vv['data'] ?>"></i> <span class="nav-label"><?= $vv['name'] ?></span><span class="<?= empty($vv['children']) ? '' : 'fa arrow'; ?>"></span></a>
                            </li>
                            <?php endforeach ?>
                        </ul>
                    </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="col-md-2">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li><a href="#" title="刷新"><i class="fa fa-home"></i>前台</a></li>
                        <li title="前台" class="hidden-xs"><a href=""><i class="fa fa-refresh"></i>刷新</a></li>
                        <li><a href="<?= Url::to(['site/logout']) ?>" title="退出"><i class="fa fa-sign-out"></i>退出</a></li>
                    </ul>
                </nav>
            </div>
            <div class="row content-tabs">
                <button class="roll-nav roll-left J_tabLeft"><i class="fa fa-backward"></i>
                </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <a href="javascript:;" class="active J_menuTab"
                           data-id="<?= Url::to(['site/main']) ?>">首页</a>
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight"><i class="fa fa-forward"></i>
                </button>
                <div class="btn-group roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">关闭操作<span
                                class="caret"></span>

                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive"><a>定位当前选项卡</a>
                        </li>
                        <li class="divider"></li>
                        <li class="J_tabCloseAll"><a>关闭全部选项卡</a>
                        </li>
                        <li class="J_tabCloseOther"><a>关闭其他选项卡</a>
                        </li>
                    </ul>
                </div>
                <a href="javascript:void(0)" onclick="reloadIframe()" class="roll-nav roll-right J_tabExit"><i class="fa fa-refresh"></i> 刷新</a>
            </div>
            <div class="row J_mainContent" id="content-main" >
                <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="<?= Url::to(['site/main']) ?>" frameborder="0" data-id="<?= Url::to(['site/main']) ?>" seamless></iframe>
            </div>
            <div class="footer">
                <div class="pull-right">
                    By：<a href="#" target="_blank">guanguan's blog</a>
                </div>
                <div>
                    <strong>Copyright</strong> 琯琯 &copy; 2014
                </div>
            </div>
        </div>
    </div>
    </div>
    <?php $this->endBody() ?>
</body>
<script>
    function reloadIframe() {
        var current_iframe = $("iframe:visible");
        current_iframe[0].contentWindow.location.reload();
        return false;
    }
</script>
</html>
<?php $this->endPage() ?>

backend/views/site/login.php
<?php
use backend\assets\LoginAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

// $this 代表视图对象
LoginAsset::register($this);
$this->params['breadcrumbs'][] = $this->title;
$this->title = '登录';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <meta name="keywords" content="H+后台主题,响应式后台">
    <meta name="description" content="H+是一个完全响应式，基于Bootstrap3最新版本开发的扁平化主题。">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body class="gray-bg">
    <?php $this->beginBody() ?>
    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name">琯</h1>
            </div>
            <!-- <h3>欢迎使用 H+</h3> -->
            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                'options' => ['class' => 'm-t'],
            ]) ?>
            <div class="form-group">
                <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'placeholder'=>$model->username])->label(false) ?>
            </div>
            <div class="form-group">
                <?= $form->field($model, 'password')->passwordInput()->label(false) ?>
            </div>
            <div class="form-group">
                <?= yii\captcha\Captcha::widget([
                    'name'=>'captchaimg',
                    'captchaAction'=>'site/captcha',
                    'imageOptions'=>[
                        'id'=>'captchaimg',
                        'title'=>'换一个',
                        'alt'=>'换一个',
                        'style'=>'cursor:pointer;',
                        'onclick' => 'this.src=this.src+"&c="+Math.random();'
                     ],
                     'template'=>'{image}'
                 ]);?>
            </div>
            <div class="form-group">
                <?= $form->field($model, 'verifyCode')->textInput()->label(false) ?>
            </div>
            <div class="form-group">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">登 录</button>
            <?php ActiveForm::end() ?>
        </div>
    </div>
    <?php $this->endBody() ?>
</body>
<?php $this->registerJs($this->blocks['captchaJS'], View::POS_END); ?>
</html>
<?php $this->endPage() ?>