backend/models/Article.php
<?php

namespace backend\models;

use Yii;
use backend\models\CategoryArticle;
use backend\models\AdminUser;


/**
 * This is the model class for table "{{%article}}".
 *
 * @property string $id
 * @property string $parent_id 父级id
 * @property int $post_type 类型,1:文章;2:页面
 * @property int $post_format 内容格式;1:html;2:md
 * @property string $user_id 发表者用户id
 * @property int $post_status 状态;1:已发布;0:未发布;
 * @property int $comment_status 评论状态;1:允许;0:不允许
 * @property int $is_top 是否置顶;1:置顶;0:不置顶
 * @property int $recommended 是否推荐;1:推荐;0:不推荐
 * @property string $post_hits 查看数
 * @property string $post_like 点赞数
 * @property string $comment_count 评论数
 * @property string $create_time 创建时间
 * @property string $update_time 更新时间
 * @property string $published_time 发布时间
 * @property string $delete_time 删除时间
 * @property string $post_title post标题
 * @property string $post_keywords seo keywords
 * @property string $post_excerpt post摘要
 * @property string $post_source 转载文章的来源
 * @property string $post_content 文章内容
 * @property string $post_content_filtered 处理过的文章内容
 * @property string $more 扩展属性,如缩略图;格式为json
 */
class Article extends \yii\db\ActiveRecord
{
    public $photos;
    public $files;
    public $thumbnail;
    public $category_id;
    public $category = [];
    public $categories;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%article}}';
    }

    public static function primaryKey()
    {
        return ['id'];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'post_type', 'post_format', 'user_id', 'post_status', 'comment_status', 'is_top', 'recommended', 'post_hits', 'post_like', 'comment_count'], 'integer'],
            [['post_content', 'post_content_filtered', 'more'], 'string'],
            [['post_title'], 'required'],
            [['post_keywords', 'post_source'], 'string', 'max' => 150],
            [['post_excerpt'], 'string', 'max' => 500],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'parent_id',
            'categories' => '分类',
            'post_type' => '类型,1:文章;2:页面',
            'post_format' => '内容格式;1:html;2:md',
            'user_id' => '作者',
            'post_status' => '状态;1:已发布;0:未发布;',
            'comment_status' => '评论状态;1:允许;0:不允许',
            'is_top' => '是否置顶;1:置顶;0:不置顶',
            'recommended' => '是否推荐;1:推荐;0:不推荐',
            'post_hits' => '点击量',
            'post_like' => '点赞量',
            'comment_count' => '评论量',
            'create_time' => '创建时间',
            'update_time' => '更新时间',
            'published_time' => '发布时间',
            'delete_time' => '删除时间',
            'post_title' => '标题',
            'post_keywords' => '关键词',
            'post_excerpt' => '摘要',
            'post_source' => '文章来源',
            'post_content' => '内容',
            'post_content_filtered' => '处理过的文章内容',
            'more' => '扩展属性,如缩略图;格式为json',
        ];
    }

    public function getCategorys()
    {
        // 文章和分类文章通过 CategoryArticle.post_id -> id 关联建立一对多关系
        return $this->hasMany(CategoryArticle::className(), ['post_id' => 'id']);
                   // ->select(['category_id']);
                   // ->asArray();
    }

    public function getAdminUser()
    {
        // 文章和分类文章通过 CategoryArticle.post_id -> id 关联建立一对一关系
        return $this->hasOne(AdminUser::className(), ['id' => 'user_id']);
    }

    /**
     * @inheritdoc
     */
    public function saveArticle($postData)
    {
        $category_ids      = $postData['category_id'];
        $more['thumbnail'] = $postData['thumbnail'];
        $more['photos']    = $postData['photos'];
        // $more['files']     = $postData['files'];
        $more['files']     = '';
        $more              = json_encode($more);

        $this->user_id        = 1;
        $this->post_title     = $postData['post_title'];
        $this->post_keywords  = json_encode(explode(',', $postData['post_keywords']));
        $this->post_source    = $postData['post_source'];
        $this->post_excerpt   = $postData['post_excerpt'];
        $this->post_content   = htmlspecialchars_decode($postData['post_content']);
        $this->published_time = $postData['published_time']? strtotime($postData['published_time']): date('Y-m-d H:i:s');
        $this->post_status    = empty($postData['post_status'])? 0: 1;
        $this->is_top         = empty($postData['is_top'])? 0: 1;
        $this->recommended    = empty($postData['recommended'])? 0: 1;
        $this->more           = $more;
        // 开启事务
        $transaction = Yii::$app->db->beginTransaction();
        try {
            // 插入文章
            $res = $this->save();
            $data = [];
            foreach ($category_ids as $val) {
                $data[] = [$this->id, $val];
            }
            // 添加或更改分类文章时，先清空
            CategoryArticle::deleteAll('post_id = :post_id ', [':post_id' => $this->id]);

            // 批量插入分类文章表
            Yii::$app->db->createCommand()->batchInsert('feehi_category_article', ['post_id','category_id'], $data)->execute();
            // 提交
            $transaction->commit();
            // return $this->redirect(['view', 'id' => $model->id]);
            return true;
        } catch (\Exception $e) {
            // 回滚
            $transaction->rollback();
            return false;
            // 抛出异常
            // throw $e;
        }
    }
}

frontend/models/Article.php
<?php
namespace frontend\models;

use yii\elasticsearch\ActiveRecord;

class Article extends ActiveRecord
{
    /**
     * 要查的属性（相当于字段）
     */
    public function attributes()
    {
        return [
            "article_id",
            "post_title",
            "post_excerpt",
            "categorys",
        ];
    }

    /**
     * 要查的索引（相当于数据库）
     */
    public static function index()
    {
        return "yii2blog";
    }

    /**
     * 要查的字段（相当于数据表）
     */
    public static function type()
    {
        return "articles";
    }

    public static function primaryKey()
    {
        return ['_id'];
    }

    public function getCategorys()
    {
        return $this->hasMany(CategoryArticle::className(), ['post_id' => 'id']);
    }

    /**
     * @return array This model's mapping
     */
    public static function mapping()
    {
        return [
            static::type() => [
                'properties' => [
                    'article_id'   => [
                        'type'     => 'long'
                    ],
                    'post_title'   => [
                        'type'     => 'string',
                        "index"    => "analyzed",
                        "analyzer" => "ik"
                    ],
                    'post_excerpt' => [
                        'type'     => 'string',
                        "index"    => "analyzed",
                        "analyzer" => "ik"
                    ],
                    'categorys'    => [
                        'type'      => 'nested',
                        'properties' => [
                            'category_names' => ['type' => 'string', 'index' => 'not_analyzed'],
                        ]
                    ]
                ]
            ],
        ];
    }

    /**
     * Set (update) mappings for this model
     */
    public static function updateMapping()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->setMapping(static::index(), static::type(), static::mapping());
    }

    /**
     * Create this model's index
     */
    public static function createIndex()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->createIndex(static::index(), [
            'settings' => [
                "refresh_interval" => "3s", //5秒后刷新
                "number_of_shards" => 1,    //分片，目前1台机器，所以为1
                "number_of_replicas" => 0   //副本为0
            ],
            'mappings' => static::mapping(),
            //'warmers' => [ /* ... */ ],
            //'aliases' => [ /* ... */ ],
            //'creation_date' => '...'
        ]);
    }

    /**
     * Delete this model's index
     */
    public static function deleteIndex()
    {
        $db = static::getDb();
        $command = $db->createCommand();
        $command->deleteIndex(static::index(), static::type());
    }

    public static function updateRecord($article_id, $columns = []){
       try{
            $record = self::get($article_id);
            foreach($columns as $key => $value){
                 $record->$key = $value;
            }

            return $record->update();
        } catch (\Exception $e){
            //handle error here
            return false;
        }
    }

    public static function deleteRecord($article_id)
    {
        try{
            $record = self::get($article_id);
            $record->delete();
            return 1;
        } catch (\Exception $e){
            //handle error here
            return false;
        }
    }

    public static function addRecord(Article $article){
        $isExist = false;

        try{
            $record = self::get($article->id);
            if(!$record){
                $record = new self();
                $record->setPrimaryKey($article->id);
            }
            else{
                $isExist = true;
            }
        } catch (\Exception $e){
            $record = new self();
            $record->setPrimaryKey($article->id);
        }

        $suppliers = [
             ['id' => '1', 'name' => 'ABC'],
             ['id' => '2', 'name' => 'XYZ'],
        ];

        $record->id   = $article->id;
        $record->name = $article->name;
        $record->author_name = $image->author_name;
        $record->status = 1;
        $record->suppliers = $suppliers;

        try{
            if(!$isExist){
                $result = $record->insert();
            }
            else{
                $result = $record->update();
            }
        } catch (\Exception $e){
            $result = false;
            //handle error here
        }

        return $result;
    }

}

backend/controllers/ArticleController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Article;
use backend\models\ArticleSearch;
use backend\models\CategoryArticle;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\helpers\ArrayHelper;
use yii\filters\VerbFilter;
use backend\components\Upload;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();
        if ($model->load(Yii::$app->request->post())) {
            $res = $model->saveArticle(Yii::$app->request->post('Article'));
            if ($res === true) {
                hintInfo(['code'=>1,'data'=>'添加成功']);
                return $this->redirect(['index']);
            } else {
                hintInfo(['code'=>0,'data'=>'添加失败'], $model);
                return $this->redirect(['create']);
            }
        }

        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $res = $model->saveArticle(Yii::$app->request->post('Article'));
            if ($res === true) {
                hintInfo(['code'=>1,'data'=>'更新成功']);

                return $this->redirect(['view', 'id' => $id]);
            } else {
                hintInfo(['code'=>0,'data'=>'更新失败'], $model);

                return $this->redirect(['update', 'id'=>$id]);
            }
        }
        // 关联模型
        $categorys = ArrayHelper::toArray($model->categorys);
        $model->category = ArrayHelper::getColumn($categorys, 'category_id');
        $model->post_keywords = implode(',', json_decode($model->post_keywords, 1));
        $model->more = json_decode($model->more, 1);
        $model->thumbnail = $model->more['thumbnail'];

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * 相册上传
     * https://packagist.org/packages/bailangzhan/yii2-webuploader
     */
    public function actionUploadImage()
    {
        /*错误时
        exit('{"code": 1, "msg": "error"}');
        正确时， 其中 attachment 指的是保存在数据库中的路径，url 是该图片在web可访问的地址
        exit('{"code": 0, "url": "http://domain/图片地址", "attachment": "图片地址"}');*/
        try {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $model = new Upload();
            $info = $model->upload('image');
            if ($info && is_array($info)) {
                return $info;
            } else {
                return ['code' => 1, 'msg' => 'error'];
            }
        } catch (\Exception $e) {
            return ['code' => 1, 'msg' => $e->getMessage()];
        }
    }


    /**
     * 文件上传
     * https://packagist.org/packages/2amigos/yii2-file-upload-widget
     */
    public function actionUploadFile()
    {
        $model = new Article();
        $imageFile = \yii\web\UploadedFile::getInstance($model, 'files');
        $directory = Yii::getAlias('@backend/web/uploader') .'/file/'. date('Ymd').'/';

        if (!is_dir($directory)) {
            \yii\helpers\FileHelper::createDirectory($directory);
        }

        if ($imageFile) {
            $uid = uniqid(time(), true);
            $fileName = $uid . '.' . $imageFile->extension;
            $filePath = $directory . $fileName;

            if ($imageFile->saveAs($filePath)) {
                $path = '/uploader/file/'. date('Ymd').'/' . $fileName;

                return \yii\helpers\Json::encode([
                    'files' => [
                        [
                            'name' => $fileName,
                            'size' => $imageFile->size,
                            'url' => $path,
                            'thumbnailUrl' => $path,
                            'deleteUrl' => 'article/delete-file?name=' . $fileName,
                            'deleteType' => 'POST',
                        ],
                    ],
                ]);
            }
        }

        return '';
    }

    /**
     * 文件上传
     * https://packagist.org/packages/2amigos/yii2-file-upload-widget
     */
    public function actionDeleteFile($name)
    {
        $directory = Yii::getAlias('@backend/web/img/temp') . DIRECTORY_SEPARATOR . Yii::$app->session->id;
        if (is_file($directory . DIRECTORY_SEPARATOR . $name)) {
            unlink($directory . DIRECTORY_SEPARATOR . $name);
        }

        $files = \yii\helpers\FileHelper::findFiles($directory);
        $output = [];
        foreach ($files as $file) {
            $fileName = basename($file);
            $path = '/img/temp/' . Yii::$app->session->id . DIRECTORY_SEPARATOR . $fileName;
            $output['files'][] = [
                'name' => $fileName,
                'size' => filesize($file),
                'url' => $path,
                'thumbnailUrl' => $path,
                'deleteUrl' => 'article/delete-file?name=' . $fileName,
                'deleteType' => 'POST',
            ];
        }
        return \yii\helpers\Json::encode($output);
    }
}

backend/views/article/create.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
?>
<div class="wrapper wrapper-content animated fadeIn" >
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title" style="padding: 0px;border-top: 0px;">
                    <ul class="nav nav-tabs">
                        <li><a href="<?=Url::to(['article/index'])?>">文章管理</a></li>
                        <li class="active"><a href="<?=Url::to(['article/create'])?>">创建文章</a></li>
                    </ul>
                </div>
                <div class="ibox-content" style="border-top: 0px;">
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="article-create">

                                <h1><?= Html::encode($this->title) ?></h1>

                                <?= $this->render('_form', [
                                    'model' => $model,
                                ]) ?>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $this->beginBlock('myjs'); ?>
    console.log('registerJs1 on page end');
<?php $this->endBlock(); ?>
<?php $this->registerJs($this->blocks['myjs'], yii\web\view::POS_END); ?>
<script>
    console.log('registerJs1 on current');
</script>

backend/views/article/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use backend\models\CategoryArticle;
use backend\models\Category;
use backend\models\AdminUser;
use yii\grid\ActionColumn;
?>
<div class="wrapper wrapper-content animated fadeIn" >
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title" style="padding: 0px;border-top: 0px;">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="">文章管理</a></li>
                        <li><a href="<?=Url::to(['article/create'])?>">创建文章</a></li>
                    </ul>
                </div>
                <div class="ibox-content" style="border-top: 0px;">
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="article-index">
                                <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
                                <?= GridView::widget([
                                    'dataProvider' => $dataProvider,
                                    'filterModel' => $searchModel,
                                    'columns' => [
                                        [
                                            // 序号列
                                            'class' => 'yii\grid\SerialColumn',
                                            // 复选框列
                                            'class' => 'yii\grid\CheckboxColumn',
                                            'options' => [
                                                'width' => '30px'
                                            ]
                                        ],

                                        [
                                            'attribute' => 'id',
                                            'options' => [
                                                'width' => '100px'
                                            ]
                                        ],
                                        [
                                            // 数据列：由于是默认类型，可以省略
                                            'class' => 'yii\grid\DataColumn',
                                            'attribute' => 'post_title',
                                            'format'=>'raw',
                                            'value' => function ($model) {
                                                $post_title = mb_substr($model->post_title, 0, 20, "UTF-8").'...';
                                                return "<a href=".Url::to(['article/view', 'id'=>$model->id]).">$post_title</a>";
                                            },
                                        ],
                                        /*[
                                            'attribute' => 'categories',
                                            'value' => function ($model) {
                                                $categorys = ArrayHelper::toArray(CategoryArticle::find()
                                                    ->where(['post_id' => $model->id])
                                                    ->select(['category_id'])
                                                    ->all());
                                                $categorys = ArrayHelper::getColumn($categorys, 'category_id');
                                                $names = '';
                                                foreach ($categorys as $k => $v) {
                                                    $names .= Category::find()->where(['id' => $v])
                                                        ->select(['name'])
                                                        ->one()['name'].',';
                                                }
                                                return mb_substr(trim($names, ','), 0, 8, "UTF-8").'...';
                                            },
                                        ],*/
                                        [
                                            'attribute' => 'user_id',
                                            'value' => function ($model) {
                                                $user_name = AdminUser::findOne($model->user_id)->username;

                                                return $user_name;
                                            },
                                            'options' => [
                                                'width' => '100px'
                                            ]
                                        ],
                                        [
                                            'attribute' => 'post_hits',
                                            'options' => [
                                                'width' => '60px'
                                            ]
                                        ],
                                        [
                                            'header' => '关键字/来源<br>摘要/缩略图',
                                            'format'=>'raw',
                                            'value' => function ($model) {
                                                $post_keywords = $model->post_keywords? '<i class="fa fa-check fa-fw text-info"></i> ': ' <i class="fa fa-close fa-fw text-danger"></i> ';
                                                $post_source   = $model->post_source? ' <i class="fa fa-check fa-fw text-info"></i> ': ' <i class="fa fa-close fa-fw text-danger"></i> ';
                                                $post_excerpt  = $model->post_excerpt? ' <i class="fa fa-check fa-fw text-info"></i> ': ' <i class="fa fa-close fa-fw text-danger"></i> ';
                                                $thumbnail     = json_decode($model->more)->thumbnail? '<i class="fa fa-photo fa-fw text-info"></i> ': ' <i class="fa fa-close fa-fw text-danger"></i> ';
                                                return $post_keywords.$post_source.$post_excerpt.$thumbnail;
                                            },
                                            'options' => [
                                                'width' => '100px'
                                            ]
                                        ],
                                        [
                                            'attribute' => 'published_time',
                                            'value' => function ($model) {
                                                return date('Y-m-d H:i:s', $model->published_time);
                                            },
                                            'options' => [
                                                'width' => '150px'
                                            ]
                                        ],
                                        [
                                            'header' => '状态',
                                            'format'=>'raw',
                                            'value' => function ($model) {
                                                $post_status = $model->post_status ? ' <i title="已发布" class="fa fa-check fa-fw text-info"></i> ': ' <i title="未发布" class="fa fa-close fa-fw text-danger"></i> ';
                                                $is_top      = $model->is_top ? ' <i title="已置顶" class="fa fa-arrow-down text-info"></i> ': ' <i title="未置顶" class="fa fa-arrow-up text-danger"></i> ';
                                                $recommended = $model->recommended ? ' <i title="已推荐" class="fa fa-thumbs-up text-info"></i> ': ' <i title="未推荐" class="fa fa-thumbs-down text-danger"></i> ';
                                                return $post_status.$is_top.$recommended;
                                            },
                                            'options' => [
                                                'width' => '70px'
                                            ]
                                        ],
                                        /*'comment_count',
                                        'post_keywords',
                                        'post_like',
                                        'post_excerpt',
                                        'post_source',
                                        'more:ntext',
                                        'post_status',
                                        'is_top',
                                        'recommended',
                                        'create_time',
                                        'update_time',
                                        'published_time',
                                        'delete_time',
                                        'comment_status',
                                        'post_type',
                                        'post_format',
                                        'post_content:ntext',
                                        'post_content_filtered:ntext',*/
                                        [
                                            // 操作列
                                            'class' => 'yii\grid\ActionColumn',
                                            'header' => '操作',
                                            'options' => [
                                                'width' => '70px'
                                            ]
                                        ],
                                    ],
                                ]); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/article/update.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
?>
<div class="wrapper wrapper-content animated fadeIn" >
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title" style="padding: 0px;border-top: 0px;">
                    <ul class="nav nav-tabs">
                        <li><a href="<?=Url::to(['article/index'])?>">文章管理</a></li>
                        <li class="active"><a href="<?=Url::to(['article/update'])?>">更新文章</a></li>
                    </ul>
                </div>
                <div class="ibox-content" style="border-top: 0px;">
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="article-create">

                                <h1><?= Html::encode($this->title) ?></h1>

                                <?= $this->render('_form', [
                                    'model' => $model,
                                ]) ?>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>